plugins {
	id 'java'
}

group = 'com.stratfat'
version = '1.6.0' // keep in sync with mod_version in ../gradle.properties

repositories {
	mavenCentral()
	maven {
		name = 'papermc'
		url = 'https://repo.papermc.io/repository/maven-public/'
	}
}

dependencies {
	compileOnly 'io.papermc.paper:paper-api:1.21.11-R0.1-SNAPSHOT'
}

tasks.withType(JavaCompile).configureEach {
	options.release = 21
	options.encoding = 'UTF-8'
}

processResources {
	def pluginVersion = project.version
	inputs.property 'version', pluginVersion
	filesMatching('plugin.yml') {
		expand 'version': pluginVersion
	}
}
